language: generic
sudo: required
services:
  - docker


before_install:
  - docker build -t kos/react-test -f ./client/Dockerfile.dev ./client

script:
#  - docker run kos/react-test npm test -- --coverage
  - docker run -e CI=true kos/react-test npm test

after_success:
  - docker build -t shaytan4/multi-client ./client
  - docker build -t shaytan4/multi-nginx ./nginx
  - docker build -t shaytan4/multi-server ./server
  - docker build -t shaytan4/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push shaytan4/multi-client
  - docker push shaytan4/multi-nginx
  - docker push shaytan4/multi-server
  - docker push shaytan4/multi-worker
